name: Deploy LLVM-CBE

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: build_full
        with:
          username: capra314cabra
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-cbe
          tags: latest
          build_args: LLVM_FILE_VERSION=9.0.1